/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zzmax_admin_ecganomalydetection_noiseTransform */

#ifndef _Included_com_zzmax_admin_ecganomalydetection_noiseTransform
#define _Included_com_zzmax_admin_ecganomalydetection_noiseTransform
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zzmax_admin_ecganomalydetection_noiseTransform
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zzmax_admin_ecganomalydetection_noiseTransform_initialize
  (JNIEnv *, jclass);

/*
 * Class:     com_zzmax_admin_ecganomalydetection_noiseTransform
 * Method:    nearKmean
 * Signature: ([[D[[D)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_com_zzmax_admin_ecganomalydetection_noiseTransform_nearKmean
  (JNIEnv *, jclass, jobjectArray, jobjectArray);

/*
 * Class:     com_zzmax_admin_ecganomalydetection_noiseTransform
 * Method:    diffKmean
 * Signature: ([[D[[D[[D)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_com_zzmax_admin_ecganomalydetection_noiseTransform_diffKmean
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jobjectArray);

/*
 * Class:     com_zzmax_admin_ecganomalydetection_noiseTransform
 * Method:    asSignal
 * Signature: ([[D)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_com_zzmax_admin_ecganomalydetection_noiseTransform_asSignal
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     com_zzmax_admin_ecganomalydetection_noiseTransform
 * Method:    detectAnomaly
 * Signature: ([[DDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_zzmax_admin_ecganomalydetection_noiseTransform_detectAnomaly
  (JNIEnv *, jclass, jobjectArray, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
